#include "textflag.h"

// Code generated by cmd/lean2rom. DO NOT EDIT.
// Source: lean/QBP/Sedenion.lean
// Issue: https://github.com/JamesPagetButler/qbp-compute-unit/issues/7
//
// Sign mask constants for the quaternion Hamilton product AVX kernel.
// Derived from the 4×4 quaternion sub-table of mulSignData in Sedenion.lean.
//
// These constants are generated and consumed directly by:
//   - emulator/qmath_amd64.s     (QW64 fast path)
//   - emulator/qmath_128_amd64.s (QW128 double-double; same masks, sign-bit
//     XOR is precision-independent)
//
// Authority chain: Lean → ROM hex → this file → asm. Closed by issues #13/#14.
// TestSIMDConstantsMatchROM parses this file at test time and verifies
// byte-for-byte agreement with the Lean-derived ROM source-of-truth.
//
// Attribution: Schafer (1954), Moreno (1998), Cawagas (2009).

// sign_x // a1 (e1/i) term sign mask
DATA qbp_lean_sign_x+0x00(SB)/8, $0x8000000000000000 // W (-)
DATA qbp_lean_sign_x+0x08(SB)/8, $0x0000000000000000 // X (+)
DATA qbp_lean_sign_x+0x10(SB)/8, $0x8000000000000000 // Y (-)
DATA qbp_lean_sign_x+0x18(SB)/8, $0x0000000000000000 // Z (+)
GLOBL qbp_lean_sign_x(SB), RODATA, $32

// sign_y // a2 (e2/j) term sign mask
DATA qbp_lean_sign_y+0x00(SB)/8, $0x8000000000000000 // W (-)
DATA qbp_lean_sign_y+0x08(SB)/8, $0x0000000000000000 // X (+)
DATA qbp_lean_sign_y+0x10(SB)/8, $0x0000000000000000 // Y (+)
DATA qbp_lean_sign_y+0x18(SB)/8, $0x8000000000000000 // Z (-)
GLOBL qbp_lean_sign_y(SB), RODATA, $32

// sign_z // a3 (e3/k) term sign mask
DATA qbp_lean_sign_z+0x00(SB)/8, $0x8000000000000000 // W (-)
DATA qbp_lean_sign_z+0x08(SB)/8, $0x8000000000000000 // X (-)
DATA qbp_lean_sign_z+0x10(SB)/8, $0x0000000000000000 // Y (+)
DATA qbp_lean_sign_z+0x18(SB)/8, $0x0000000000000000 // Z (+)
GLOBL qbp_lean_sign_z(SB), RODATA, $32

// conj // quaternion conjugate mask [+,-,-,-]
DATA qbp_lean_conj+0x00(SB)/8, $0x0000000000000000 // W (+)
DATA qbp_lean_conj+0x08(SB)/8, $0x8000000000000000 // X (-)
DATA qbp_lean_conj+0x10(SB)/8, $0x8000000000000000 // Y (-)
DATA qbp_lean_conj+0x18(SB)/8, $0x8000000000000000 // Z (-)
GLOBL qbp_lean_conj(SB), RODATA, $32

