#!/usr/bin/env bash
# qbp-cu-baseline.sh — regenerate the QBP-CU performance baseline (issue: between-sprint
# test prep). Captures a REPRODUCIBLE, environment-stamped benchmark record so future
# runs can be diffed against it (with `benchstat`) to see improvements/regressions.
#
# Usage:   scripts/qbp-cu-baseline.sh [COUNT]        (COUNT default 6, for benchstat validity)
# Output:  doc/benchmarks/raw/qbp-cu-bench-<git-sha>-<date>.txt   (raw, benchstat-ready)
#
# Discipline (federation resource gates):
#   • Run on a QUIET box — contended benchmarks make a bad baseline. This script
#     REFUSES to run if load is high, so a noisy capture can't silently become the record.
#   • Bounded: GOMAXPROCS=2, nice, and a hard timeout.
# Compare two captures:  benchstat old.txt new.txt
set -euo pipefail

COUNT="${1:-6}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

# --- resource guard: refuse a noisy capture -------------------------------------------
LOAD1=$(awk '{print $1}' /proc/loadavg)
NCPU=$(nproc)
# refuse if 1-min load exceeds ~half the cores (a busy box gives an untrustworthy baseline)
if awk "BEGIN{exit !($LOAD1 > $NCPU/2)}"; then
  echo "REFUSING: 1-min load $LOAD1 on $NCPU cores is too high for a clean baseline." >&2
  echo "  A contended capture produces inflated ns/op that mis-sets the record. Wait for a quiet box." >&2
  exit 1
fi

SHA=$(git rev-parse --short HEAD)
DATE=$(date -u +%Y-%m-%d)
OUTDIR="doc/benchmarks/raw"
mkdir -p "$OUTDIR"
OUT="$OUTDIR/qbp-cu-bench-${SHA}-${DATE}.txt"

# --- environment stamp (reproducibility metadata; a baseline without it is uncomparable) ---
{
  echo "# QBP-CU benchmark baseline — raw \`go test -bench\` output (benchstat-ready)"
  echo "# generated by scripts/qbp-cu-baseline.sh"
  echo "date:        $(date -u +%FT%TZ)"
  echo "git_sha:     $(git rev-parse HEAD)"
  echo "git_short:   $SHA"
  echo "go_version:  $(go version | awk '{print $3}')"
  echo "cpu_model:   $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2 | xargs)"
  echo "cpu_cores:   $NCPU"
  echo "gomaxprocs:  2"
  echo "count:       $COUNT"
  echo "load_1min:   $LOAD1   (at capture start)"
  echo "mem_free_gb: $(free -g | awk '/Mem:/{print $7}')"
  # Which quaternion kernel path is live matters (AVX-FMA vs scalar) — record it or
  # comparisons across hosts are apples-to-oranges.
  echo "cpu_avx2:    $(grep -qm1 avx2 /proc/cpuinfo && echo yes || echo no)"
  echo "cpu_fma:     $(grep -qm1 fma /proc/cpuinfo && echo yes || echo no)"
  echo
} > "$OUT"

echo "Capturing baseline → $OUT  (count=$COUNT, GOMAXPROCS=2)…"
GOMAXPROCS=2 timeout 900 nice -n 10 \
  go test -C emulator -run '^$' -bench '.' -benchmem -count="$COUNT" ./... 2>&1 | tee -a "$OUT"

echo
echo "Done → $OUT"
echo "Compare a later run:  benchstat \"$OUT\" <new-capture>.txt"
