// Code generated by cmd/lean2rom. DO NOT EDIT.
// Source: lean/QBP/Sedenion.lean
// Issue: https://github.com/JamesPagetButler/qbp-compute-unit/issues/7
//
// Quaternion sign constants derived from the sedenion sign table.
// The ℍ (quaternion) algebra is the sub-algebra of 𝕊 at indices 0..3.
//
// Attribution: Schafer (1954) CD construction; Moreno (1998) XOR-index lemma.
//
// sign[i][j] encodes the sign of e_i × e_j.
// +1 = positive component, -1 = negative component.
// Index of product = i XOR j (always, by XOR-index lemma).
package roms

// QuaternionSignTable is the 4×4 sign matrix for quaternion multiplication.
// Row i, column j: sign of e_i × e_j = QuaternionSignTable[i][j] × e_{i^j}.
var QuaternionSignTable = [4][4]int8{
	{+1, +1, +1, +1}, // row e0/1
	{+1, -1, +1, -1}, // row e1/i
	{+1, -1, -1, +1}, // row e2/j
	{+1, +1, -1, -1}, // row e3/k
}

// The following sign bits are extracted from QuaternionSignTable
// and correspond to the sign-mask lanes in emulator/qmath_amd64.s:
//
//   qbp_lean_sign_x: applied to a1 (e1/i) component across [W,X,Y,Z] lanes
//   qbp_lean_sign_y: applied to a2 (e2/j) component across [W,X,Y,Z] lanes
//   qbp_lean_sign_z: applied to a3 (e3/k) component across [W,X,Y,Z] lanes
//
// The asm shuffle for term k places b_{k^0},b_{k^1},b_{k^2},b_{k^3} in
// positions [W,X,Y,Z]. The sign mask for term k in output component r is:
//   SignForAsmMask[k][r] = sign16[k][k^r]

// SignYSignX[r] = sign of e1 × e_{1 XOR r} for r in {0,1,2,3} → lanes {W,X,Y,Z}
var SignYSignX = [4]int8{-1, +1, -1, +1} // asm qbp_lean_sign_x: should be [-1,+1,-1,+1]

// SignYSignY[r] = sign for e2 × e_{...} term, for lanes {W,X,Y,Z}
var SignYSignY = [4]int8{-1, +1, +1, -1} // asm qbp_lean_sign_y: should be [-1,+1,+1,-1]

// SignYSignZ[r] = sign for e3 × e_{...} term, for lanes {W,X,Y,Z}
var SignYSignZ = [4]int8{-1, -1, +1, +1} // asm qbp_lean_sign_z: should be [-1,-1,+1,+1]
